### ISSUE TITLE
feature: 请求增加采集js动态加载页面功能

### ISSUE THREAD

**Issue by charmingYouYou** [fbtopcn/fatratcollect#14]
采集掘金列表, 掘金反爬虫导致无法获取列表的相关ul & li的dom
链接: https://juejin.im/welcome/frontend
![4f186180e06745bd7c3f37907225530](https://user-images.githubusercontent.com/31199453/66586932-0d3d2200-ebbc-11e9-987d-2ec30aa01fd1.png)
![34ee1d60dd8d60c50c5b8c6043c4e72](https://user-images.githubusercontent.com/31199453/66586947-13cb9980-ebbc-11e9-88fa-af6abdb01ec8.png)

**Comment by charmingYouYou** [comment]
重新调试了下,不是请求header的问题, 应该是掘金列表信息是动态js加载的, 直接采集会拿不到列表的dom

**Comment by KitePig** [comment]
采集js内容需要安装 nodejs 依赖，一个php插件无法完成此操作。建议自己2次开发使用。

**Comment by KitePig** [comment]
恕我直言, 胖鼠V2.0后 可以实现
