### ISSUE TITLE
采集中心报错

### ISSUE THREAD

**Issue by st-youth** [fbtopcn/fatratcollect#15]
最初安装插件后测试过，一切正常。一段时间没用之后，再次点击胖鼠的侧边栏之后出现以下报错：

`Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Client::request() in /www/wwwroot/evolutionofear.com/wp-content/plugins/fat-rat-collect/includes/fatrat-validation.php:111 Stack trace: #0 /www/wwwroot/evolutionofear.com/wp-content/plugins/fat-rat-collect/includes/fatrat-validation.php(99): FRC_Validation->validation_request('/validation/ann...') #1 /www/wwwroot/evolutionofear.com/wp-content/plugins/fat-rat-collect/includes/fatrat-spider.php(578): FRC_Validation->announcement() #2 /www/wwwroot/evolutionofear.com/wp-includes/class-wp-hook.php(286): frc_spider('') #3 /www/wwwroot/evolutionofear.com/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /www/wwwroot/evolutionofear.com/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #5 /www/wwwroot/evolutionofear.com/wp-admin/admin.php(253): do_action('%e8%83%96%e9%bc...') #6 {main} thrown in /www/wwwroot/evolutionofear.com/wp-content/plugins/fat-rat-collect/includes/fatrat-validation.php on line 111`
The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

其他子页面均正常。卸载后重装也不能解决。

如图所示
<img width="1092" alt="Traceback Screen Shot" src="https://user-images.githubusercontent.com/43197312/67233078-27f17f80-f475-11e9-993a-899362506f45.png">

**Comment by KitePig** [comment]
这个错误不影响采集。你先把debug模式关闭。后续版本会优化
