### ISSUE TITLE
超时! 亲不必惊慌, 胖鼠为你保驾护航. 此异常一般是你的网络太差或服务器带宽小.....

### ISSUE THREAD

**Issue by Lemonwck** [fbtopcn/fatratcollect#16]
超时! 亲不必惊慌, 胖鼠为你保驾护航. 此异常一般是你的网络太差或服务器带宽小,文章中图片过多,下载图片太慢,时间久了就超时了(但是采集任务仍在后台运行哦), 你可以新开窗口去数据中心看一下. 是不是已经采集成功一部分了? 可以修改(php.ini)请求超时时间选项可优化。或者重新点击一次运行即可(推荐)，但是多等一会再点哦(30秒左右吧), 因为上一个后台任务还没结束, 又点了一次 文章滤重功能可能会失效造成文章重复采集哦, 没有其他影响 = - =!

请问这个怎么解决！！！

**Comment by Lemonwck** [comment]
请问楼主php.ini 在那个文件夹底下 怎么修改这个问题 我知道我服务器带宽下 但是也不至于一篇文章也下载不下来吧，请求直接报500 怎么修改一下呢？
请楼主给一个解决方案

**Comment by Lemonwck** [comment]
点击请求直接报500

**Comment by KitePig** [comment]
等很久这个报错是正常的。点击立即报错，属于规则有错误,  胖鼠采集 V2.0 后会尽量优化这些错误

**Comment by gayhub-dev** [comment]
500 Error,请检查php错误信息,若有
`PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in .......`
请尝试安装
`apt/yum install php-xml`
后重启php服务

**Comment by KitePig** [comment]
😂

gayhub-dev <notifications@github.com> 于2020年5月10日周日 下午12:04写道：
