### ISSUE TITLE
【建议优化】能不能搞得简单的一些啊？没有门槛的？现在的门槛太高了

### ISSUE THREAD

**Issue by ghost** [fbtopcn/fatratcollect#18]
比如针对微信公众号的设置一套模板
针对简书的设置一套模板
针对zendesk的设置一套模板，这样大家就直接用了，你这样，虽然做的很好，可能有很大的门槛的，对于技术小白，实在不会用的

**Comment by KitePig** [comment]
胖鼠采集发版第一天开始, 微信, 简书 可直接使用, 为什么需要自己写配置呢?

**Comment by ghost** [comment]
怎么使用？有那种教程吗？
我说的简单是指比如输入一个公众号ID或者其他方式，点个按钮就好了，不需要配置代码


 原始邮件 
发件人: 深渊胖鼠<notifications@github.com>
收件人: fbtopcn/fatratcollect<fatratcollect@noreply.github.com>
抄送: jiazhaoyang<1285828365@qq.com>; Author<author@noreply.github.com>
发送时间: 2020年4月1日(周三) 12:13
主题: Re: [fbtopcn/fatratcollect] 【建议优化】能不能搞得简单的一些啊？没有门槛的？现在的门槛太高了 (#18)


微信, 简书 可直接使用, 谁告诉你需要自己写配置呢?

**Comment by KitePig** [comment]
其他疑问请参考官网 https://www.fatrat.cn

**Comment by ghost** [comment]
针对微信公众号或者简书的，能不能举个例子？
