### ISSUE TITLE
针对微信公众号或者简书的，能不能举个例子？

### ISSUE THREAD

**Issue by ghost** [fbtopcn/fatratcollect#20]
针对微信公众号或者简书的，能不能举个例子？
就是有一些模板配置之类的东西？现在你们做的东西太程序员化了

**Comment by KitePig** [comment]
上个issues我关掉了, 你可能没看明白. 我再给你详细说一遍
微信和简书 在采集中心直接键入网址即可采集,并且一次可采集多个, 采集过一次后配置中心会自动生成对应的配置. 所以不需要你来写规则.
关于新建规则, 官网( https://www.fatrat.cn )有视频教程, 文字教程, 配置中心 还有一键导入默认例子的功能, 直接会提供给你5个写好的例子, 可立刻使用, 无需任何配置 鼠友还有QQ群, 大家有问题群内会有很多热心鼠帮助你. 
最后, 目前插件只有我一个人维护, 并没有我们.
