### ISSUE TITLE
你好，有段数据采集不完整

### ISSUE THREAD

**Issue by iwanttodo1t** [fbtopcn/fatratcollect#25]
wordpress版本：5.4.2版本
插件版本：2.2.4版本

采集范围是：#review
采集content的选择器是：#sf_description，html，a -img
最后只能得到：`<i id="revintroline">aaaaaaaaaaaaa</i>`，而无法得到该标签下面的兄弟元素，兄弟元素是text，不是标签。

哎，github竟然不支持插入html代码，噗。

**Comment by KitePig** [comment]
请把目标网址贴出来看看

**Comment by iwanttodo1t** [comment]
> 请把目标网址贴出来看看

https://www.snapfiles.com/get/wysiwygwbuilder.html

**Comment by KitePig** [comment]
![image](https://user-images.githubusercontent.com/24408061/87239414-74d11800-c441-11ea-99ae-97cc2e2baca5.png)
![image](https://user-images.githubusercontent.com/24408061/87239433-b3ff6900-c441-11ea-847b-70d319290f92.png)
可以获取到，浏览器预览时折行了，可鼠标放上去预览。也可以在response中查看

**Comment by iwanttodo1t** [comment]
好的，明白了

**Comment by iwanttodo1t** [comment]
有考虑过增加翻译功能么？

**Comment by KitePig** [comment]
有计划做，暂时没时间
