### ISSUE TITLE
采集到的链接不全怎么办

### ISSUE THREAD

**Issue by q286127285** [fbtopcn/fatratcollect#27]
现在的规则是域名+采集到的a标签的链接 比如  http://aaa.com/bbb.html
我遇到了有些站点域名后面加了目录 然后再加采集到的a标签的链接 才是真正的详情页地址  http://aaa.com/111112/bbb.html

**Comment by KitePig** [comment]
相对链接都会补全
/bbb.html 补全域名
bbb.html 补全域名+当前目录
