### ISSUE TITLE
我采集发现失败，楼主可否帮我检查下？

### ISSUE THREAD

**Issue by ifp1090** [fbtopcn/fatratcollect#8]
你好！感谢提供采集插件！
我计划采集这个网站的文章：
http://www.guandian.cn/news/
根据操作方法论，我依次执行了采集规则编写：
![](http://pbox.online/20190529122917.png)
但我发现并不能成功采集到文章，请问我的问题出现在什么地方？
谢谢！

**Comment by KitePig** [comment]
列表规则是错的。
详情规则是对的  但是少了 . 
请使用debug功能
