### ISSUE TITLE
可以考虑增加反爬虫功能

### ISSUE THREAD

**Issue by szchengmi** [fbtopcn/fatratcollect#9]
也许作者可以考虑整合上爬虫，毕竟采集这货最怕的就是反爬虫

**Comment by KitePig** [comment]
整合上爬虫什么意思？ 目前的大家采集量还不至于被反

**Comment by szchengmi** [comment]
我和我朋友都被反了,也就集中在搜狗微信搜索采集这里


------------------ 原始邮件 ------------------
发件人: "fubo"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 晚上7:13
收件人: "fbtopcn/fatratcollect"<fatratcollect@noreply.github.com>;
抄送: "szchengmi"<247571488@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fbtopcn/fatratcollect] 也许作者可以考虑整合上爬虫 (#9)




整合上爬虫什么意思？ 目前的大家采集量还不至于被反

**Comment by KitePig** [comment]
不建议采集搜索引擎，有这方面需求请自行改代码调试。99%的鼠还是到不了被反采集的地步。
